#!/usr/bin/perl -w

use strict;
use Getopt::Long;
use Stuff::Debug qw(&db_out);
use Stuff::Usage qw(&usage &long_usage &version_message);

use constant STUFF_PROG_DESCRIPTION => "Shuffle list";
use constant STUFF_PROG_COPYRIGHT   => "(C) 2005; released under the GNU GPL version 2";
use constant STUFF_PROG_VERSION     => "0.01";
use constant STUFF_PROG_AUTHOR      => "Matthew Gates";

BEGIN {
    db_out(1, "program starting");
}

END {
    db_out(1, "program exiting with status " . ($? || 0));
}

GetOptions(
	   'help'              => sub { long_usage(0) },
	   'version'           => sub { version_message(); exit 0; },
	   'debug=i'           => \$Stuff::Debug::debug_level{S},
	   )     or usage(1);

my @ga_data;
my %gh_keys;

if ( $#ARGV < 0 ) {
    while(<>) {
	chomp;
	push @ga_data, $_;
    }
} else {
    @ga_data = @ARGV;
}

for (my $i=0; $i<=$#ga_data; $i++) {
    $gh_keys{$i} = rand();
}

foreach my $key (sort { $gh_keys{$a} <=> $gh_keys{$b} } keys %gh_keys) {
    print $ga_data[$key] . "\n";
}

exit 0;


__END__

=head1 NAME 

shuffle - re-arrange a list in random order

=head1 SYNOPSIS

shuffle [options] [list]

=head1 DESCRIPTION

Reads a list of parameters from the command line, or, failing that, a
list of lines from standard input.

Outputs same list of parameters, sorted by some random values -
i.e. shuffled about.

=head1 OPTIONS

=over

=item B<--debug>=I<level>

Print diagnostic messages while executing.  The value of I<level> must be an
integer.  The higher the number, the more verbose the diagnostic output will
be.

=item B<--help>

Print the command line syntax an option details.

=item B<--version>

Print the program description and version.

=back

=head1 ENVIRONMENT

=over

=item STUFF_?_DBLEVEL

Sets debugging levels.  The ? can be D for database, M for module,
or S for script debugging messages.  Generally only S and D are
interesting for users, M is mostly just used during development.

=back

=head1 FILES

N/A

=head1 LICENSE

shuffle is released under the GNU GPL (version 2, June 1991).  A
copy of the license should have been provided in the distribution of
the software in a file called "LICENSE".  If you can't find this, then
try here: http://www.gnu.org/copyleft/gpl.html

=head1 AUTHOR

Matthew Gates <matthew@porpoisehead.net>

http://porpoisehead.net/

=head1 CHANGELOG

=over

=item Date:2005-05-25 Created, Author MNG

Original version.

=back

=head1 BUGS

Please report bugs to the author.

=head1 SEE ALSO


=cut

